name: osint-foresight
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.2
  - pyyaml>=6
  - requests>=2.32
  - python-dotenv>=1.0
  - tqdm>=4.66
  - rich>=13.7
  - pip
  - pip:
      - google-cloud-bigquery
      - openpyxl