# OSINT Foresight Pull Configuration
# Defines data collection settings for all 44 countries

# Data storage configuration
storage:
  base_path: F:/OSINT_Data
  backup_path: F:/OSINT_Backups
  max_storage_gb: 2000  # 2TB limit
  compression: true
  retention_days:
    raw: 90
    processed: 365
    reports: -1  # Keep forever

# Pull frequencies by data type
frequencies:
  real_time:
    - vessel_tracking
    - news_monitoring

  daily:
    - patent_filings
    - regulatory_updates

  weekly:
    - crossref_publications
    - crossref_events
    - github_activity
    - standards_updates

  monthly:
    - cordis_projects
    - ted_procurement
    - worldbank_indicators
    - oecd_statistics
    - eurostat_data
    - gleif_entities
    - ietf_participation
    - openaire_research
    - national_procurement

  quarterly:
    - commoncrawl_intelligence
    - supply_chain_mapping
    - technology_landscape

  yearly:
    - openalex_snapshot
    - patent_landscape
    - comprehensive_assessment

# Country-specific configurations
countries:
  # Priority 1: Major EU economies
  DE:
    priority: 1
    languages: [de, en]
    special_sources:
      - destatis  # German statistics office
      - dpma  # German patent office
      - bmwk  # Economic ministry data
    procurement_portals:
      - evergabe-online.de
      - vergabe24.de

  FR:
    priority: 1
    languages: [fr, en]
    special_sources:
      - insee  # French statistics
      - inpi  # French patents
    procurement_portals:
      - marches-publics.gouv.fr
      - boamp.fr

  IT:
    priority: 1
    languages: [it, en]
    special_sources:
      - istat  # Italian statistics
    procurement_portals:
      - acquistinretepa.it

  ES:
    priority: 1
    languages: [es, en]
    special_sources:
      - ine  # Spanish statistics
    procurement_portals:
      - contrataciondelestado.es

  NL:
    priority: 1
    languages: [nl, en]
    special_sources:
      - cbs  # Dutch statistics
    procurement_portals:
      - tenderned.nl

  PL:
    priority: 1
    languages: [pl, en]
    special_sources:
      - stat.gov.pl
    procurement_portals:
      - uzp.gov.pl

  # Priority 2: Smaller EU & strategic partners
  AT:
    priority: 2
    languages: [de, en]
    special_sources:
      - statistik.at
    procurement_portals:
      - bbg.gv.at

  BE:
    priority: 2
    languages: [nl, fr, en]
    procurement_portals:
      - publicprocurement.be

  SE:
    priority: 2
    languages: [sv, en]
    special_sources:
      - scb.se  # Swedish statistics
    procurement_portals:
      - tendsign.se

  DK:
    priority: 2
    languages: [da, en]
    procurement_portals:
      - udbud.dk

  FI:
    priority: 2
    languages: [fi, en]
    procurement_portals:
      - hankintailmoitukset.fi

  NO:
    priority: 2
    languages: [no, en]
    special_sources:
      - ssb.no  # Norwegian statistics
    procurement_portals:
      - doffin.no

  CH:
    priority: 2
    languages: [de, fr, it, en]
    special_sources:
      - bfs.admin.ch  # Swiss statistics
    procurement_portals:
      - simap.ch

  # Priority 3: EU candidates & others
  TR:
    priority: 3
    languages: [tr, en]
    special_sources:
      - tuik.gov.tr
    procurement_portals:
      - ekap.kik.gov.tr

  UA:
    priority: 3
    languages: [uk, en]
    special_sources:
      - ukrstat.gov.ua
    procurement_portals:
      - prozorro.gov.ua

  GB:
    priority: 3
    languages: [en]
    special_sources:
      - ons.gov.uk
      - companies-house.gov.uk
    procurement_portals:
      - find-tender.service.gov.uk
      - contractsfinder.service.gov.uk

  # Continue for all 44 countries...
  # (Abbreviated for space - full list includes all 44)

# Technology areas of interest for Common Crawl
technology_areas:
  artificial_intelligence:
    keywords:
      - artificial intelligence
      - machine learning
      - deep learning
      - neural network
      - computer vision
      - natural language processing
      - reinforcement learning
    frameworks:
      - TensorFlow
      - PyTorch
      - scikit-learn
      - Keras
      - JAX
      - Hugging Face

  quantum_computing:
    keywords:
      - quantum computing
      - quantum algorithm
      - quantum supremacy
      - quantum annealing
      - quantum cryptography
      - QKD
    companies:
      - IBM Quantum
      - IonQ
      - Rigetti
      - D-Wave
      - PsiQuantum

  biotechnology:
    keywords:
      - CRISPR
      - gene editing
      - synthetic biology
      - mRNA
      - proteomics
      - bioinformatics

  semiconductors:
    keywords:
      - semiconductor
      - chip design
      - EUV lithography
      - ASML
      - TSMC
      - foundry
      - fab

  clean_energy:
    keywords:
      - renewable energy
      - solar panel
      - wind turbine
      - hydrogen fuel
      - battery storage
      - grid storage

  cybersecurity:
    keywords:
      - zero trust
      - threat intelligence
      - SIEM
      - SOC
      - ransomware
      - supply chain security

  blockchain:
    keywords:
      - blockchain
      - distributed ledger
      - smart contract
      - DeFi
      - Web3
      - cryptocurrency

# API rate limits and credentials
api_limits:
  crossref:
    requests_per_second: 10
    daily_limit: 100000

  worldbank:
    requests_per_minute: 120

  eurostat:
    requests_per_second: 5

  oecd:
    requests_per_minute: 60

  ted:
    requests_per_hour: 1000

  commoncrawl:
    concurrent_downloads: 5
    bandwidth_mbps: 100

# Monitoring and alerts
monitoring:
  slack_webhook: ${SLACK_WEBHOOK_URL}
  email_alerts: osint-alerts@example.com

  alert_conditions:
    - pull_failure_count > 10
    - storage_usage > 90%
    - api_rate_limit_exceeded
    - new_critical_technology_detected

  report_schedule:
    daily_summary: "06:00"
    weekly_report: "Monday 09:00"
    monthly_analysis: "1st 10:00"

# Data processing pipeline
processing:
  stages:
    - raw_collection
    - validation
    - normalization
    - entity_extraction
    - relationship_mapping
    - risk_scoring
    - report_generation

  parallel_workers: 4
  batch_size: 1000

# Backup strategy
backup:
  frequency: daily
  retention:
    daily: 7
    weekly: 4
    monthly: 12

  destinations:
    - F:/OSINT_Backups
    - Google Cloud Storage (optional)

# Data quality checks
quality_checks:
  completeness:
    min_coverage: 0.8  # 80% of expected data

  freshness:
    max_age_days:
      real_time: 1
      daily: 2
      weekly: 10
      monthly: 35

  accuracy:
    validation_rules:
      - country_codes_valid
      - dates_in_range
      - numeric_values_reasonable
      - no_duplicate_records
