#!/usr/bin/env python3
"""
Analyze manual validation results and calculate actual precision
"""

import pandas as pd
from pathlib import Path
from datetime import datetime

REVIEW_DIR = Path("C:/Projects/OSINT - Foresight/analysis/manual_review")

def analyze_sheet(df, sheet_name):
    """Analyze results from one sheet"""
    results = {
        'source': sheet_name,
        'total': len(df),
        'true_positives': 0,
        'false_positives': 0,
        'uncertain': 0,
        'not_reviewed': 0,
        'precision': 0.0,
        'false_positive_examples': []
    }

    for idx, row in df.iterrows():
        review = str(row.get('is_true_positive', '')).strip().upper()

        if review == 'YES':
            results['true_positives'] += 1
        elif review == 'NO':
            results['false_positives'] += 1
            # Collect false positive examples
            if len(results['false_positive_examples']) < 10:
                example = {
                    'record': row.get('recipient_name') or row.get('contractor_name') or row.get('assignee_name') or row.get('title', 'N/A'),
                    'notes': row.get('notes', '')
                }
                results['false_positive_examples'].append(example)
        elif review == 'UNCERTAIN':
            results['uncertain'] += 1
        else:
            results['not_reviewed'] += 1

    # Calculate precision (excluding uncertain and not reviewed)
    reviewed = results['true_positives'] + results['false_positives']
    if reviewed > 0:
        results['precision'] = (results['true_positives'] / reviewed) * 100
    else:
        results['precision'] = 0.0

    return results

def main():
    """Main analysis function"""
    print("="*80)
    print("PRECISION VALIDATION - ANALYSIS OF MANUAL REVIEW")
    print("="*80)

    # Find latest review file
    review_files = list(REVIEW_DIR.glob("precision_validation_samples_*.xlsx"))

    if not review_files:
        print("\n[ERROR] No review files found in:", REVIEW_DIR)
        print("\nPlease complete manual review first using the Excel file generated by sample_for_manual_validation.py")
        return

    # Get most recent
    latest_file = max(review_files, key=lambda p: p.stat().st_mtime)
    print(f"\nReview file: {latest_file.name}")
    print(f"Last modified: {datetime.fromtimestamp(latest_file.stat().st_mtime)}")

    # Read all sheets
    xl_file = pd.ExcelFile(latest_file)
    sheet_names = [s for s in xl_file.sheet_names if s != 'Instructions']

    print(f"\nSheets found: {', '.join(sheet_names)}")

    results = []

    print("\n" + "="*80)
    print("RESULTS BY DATA SOURCE")
    print("="*80)

    for sheet in sheet_names:
        df = pd.read_excel(latest_file, sheet_name=sheet)
        result = analyze_sheet(df, sheet)
        results.append(result)

        print(f"\n{result['source']}:")
        print(f"  Total reviewed: {result['total']}")
        print(f"  True positives: {result['true_positives']} ({result['true_positives']/result['total']*100:.1f}%)")
        print(f"  False positives: {result['false_positives']} ({result['false_positives']/result['total']*100:.1f}%)")
        print(f"  Uncertain: {result['uncertain']} ({result['uncertain']/result['total']*100:.1f}%)")
        print(f"  Not reviewed: {result['not_reviewed']} ({result['not_reviewed']/result['total']*100:.1f}%)")
        print(f"  PRECISION: {result['precision']:.1f}%")

        if result['false_positive_examples']:
            print(f"\n  False positive examples:")
            for i, ex in enumerate(result['false_positive_examples'][:5], 1):
                print(f"    {i}. {ex['record']}")
                if ex['notes']:
                    print(f"       Note: {ex['notes']}")

    # Overall statistics
    print("\n" + "="*80)
    print("OVERALL SUMMARY")
    print("="*80)

    total_all = sum(r['total'] for r in results)
    tp_all = sum(r['true_positives'] for r in results)
    fp_all = sum(r['false_positives'] for r in results)
    unc_all = sum(r['uncertain'] for r in results)
    not_rev_all = sum(r['not_reviewed'] for r in results)

    reviewed_all = tp_all + fp_all
    overall_precision = (tp_all / reviewed_all * 100) if reviewed_all > 0 else 0.0

    print(f"\nTotal records: {total_all}")
    print(f"True positives: {tp_all} ({tp_all/total_all*100:.1f}%)")
    print(f"False positives: {fp_all} ({fp_all/total_all*100:.1f}%)")
    print(f"Uncertain: {unc_all} ({unc_all/total_all*100:.1f}%)")
    print(f"Not reviewed: {not_rev_all} ({not_rev_all/total_all*100:.1f}%)")
    print(f"\n{'='*80}")
    print(f"OVERALL PRECISION: {overall_precision:.1f}%")
    print(f"{'='*80}")

    # Comparison with estimates
    print("\n" + "="*80)
    print("COMPARISON WITH ESTIMATES")
    print("="*80)

    print(f"\nEstimated precision (from improvements): 97%")
    print(f"Actual precision (from manual review): {overall_precision:.1f}%")
    difference = overall_precision - 97
    print(f"Difference: {difference:+.1f} percentage points")

    if overall_precision >= 95:
        print("\nStatus: EXCELLENT - Precision target achieved!")
    elif overall_precision >= 90:
        print("\nStatus: GOOD - Precision is strong, minor improvements possible")
    elif overall_precision >= 85:
        print("\nStatus: ACCEPTABLE - Consider additional false positive filters")
    else:
        print("\nStatus: NEEDS IMPROVEMENT - Review false positive patterns")

    # Save results to JSON
    output_file = REVIEW_DIR / f"precision_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    import json
    with open(output_file, 'w') as f:
        json.dump({
            'review_file': latest_file.name,
            'analysis_date': datetime.now().isoformat(),
            'results_by_source': results,
            'overall': {
                'total': total_all,
                'true_positives': tp_all,
                'false_positives': fp_all,
                'uncertain': unc_all,
                'not_reviewed': not_rev_all,
                'precision': overall_precision
            }
        }, f, indent=2)

    print(f"\nDetailed results saved to: {output_file.name}")

if __name__ == "__main__":
    main()
