name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip && pip install -r requirements.txt
      - name: Smoke test (PT)
        run: |
          python -m src.analysis.phase2_landscape --country PT
          python -m src.analysis.phase5_links --country PT
      - name: Validate processed schemas (if exist)
        run: |
          python - <<'PY'
          import sys, os, glob
          from pathlib import Path
          from src.utils.io import SCHEMAS, processed_path
          country='PT'
          base=Path('data/processed')/f'country={country}'
          if base.exists():
            for fname, headers in SCHEMAS.items():
              p = base/fname
              if p.exists():
                first=open(p,'r',encoding='utf-8').readline().strip().replace('\ufeff','')
                delim='\t' if p.suffix=='.tsv' else ','
                got=first.split(delim)
                assert got==headers, f"Header mismatch in {p}"
          print('schema_ok')
          PY